# Generated by Django 3.0.2 on 2021-10-06 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Feedapp', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraineeProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_admitted', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(default='others', on_delete=django.db.models.deletion.CASCADE, to='Feedapp.Course')),
            ],
        ),
    ]
