# Generated by Django 3.0.2 on 2021-10-06 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Feedapp', '0001_initial'),
        ('Trainee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traineeprofile',
            name='course',
            field=models.ForeignKey(default='Others', on_delete=django.db.models.deletion.CASCADE, to='Feedapp.Course'),
        ),
    ]
