# Generated by Django 3.1.7 on 2021-10-13 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Feedapp', '0007_auto_20211013_2120'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Trainee', '0002_auto_20211006_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traineeprofile',
            name='course',
        ),
        migrations.CreateModel(
            name='CourseTaken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(default='Others', on_delete=django.db.models.deletion.CASCADE, to='Feedapp.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
