# Generated by Django 3.1.7 on 2021-10-14 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trainee', '0003_auto_20211013_2120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursetaken',
            options={'verbose_name_plural': 'Taken Courses by Trainees'},
        ),
    ]
