# Generated by Django 3.0.2 on 2021-10-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='phone',
            field=models.IntegerField(blank=True, max_length=13, null=True),
        ),
    ]
