# Generated by Django 3.0.2 on 2021-10-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_auto_20211006_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
