# Generated by Django 3.1.7 on 2021-10-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0006_auto_20211022_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='photo',
            field=models.ImageField(default=None, upload_to='Employee_Photos'),
        ),
    ]
