# Generated by Django 3.1.7 on 2021-10-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0007_auto_20211022_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='photo',
            field=models.ImageField(blank=True, default=None, upload_to='Employee_Photos'),
        ),
    ]
