# Generated by Django 3.1.7 on 2021-10-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0008_auto_20211022_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='photo',
            field=models.ImageField(default='static/img/default_avatar.png', upload_to='Employee_Photos'),
        ),
    ]
