# Generated by Django 3.2.5 on 2021-10-28 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Feedapp', '0015_alter_department_incharge'),
        ('Employee', '0010_auto_20211022_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='department',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Feedapp.department'),
        ),
    ]
