# Generated by Django 3.0.2 on 2021-10-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q1', models.TextField(max_length=100)),
                ('Q2', models.TextField(max_length=100)),
                ('Q3', models.TextField(max_length=100)),
                ('Q4', models.TextField(max_length=100)),
                ('Q5', models.TextField(max_length=100)),
                ('Q6', models.TextField(max_length=100)),
                ('Q7', models.TextField(max_length=100)),
                ('Q8', models.TextField(max_length=100)),
                ('Q9', models.TextField(max_length=100)),
                ('Q10', models.TextField(max_length=100)),
                ('Q11', models.TextField(max_length=100)),
                ('Q12', models.TextField(max_length=100)),
            ],
        ),
    ]
