# Generated by Django 3.0.2 on 2021-10-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedapp', '0003_auto_20211006_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='A13',
            field=models.CharField(choices=[('POOR', 'POOR'), ('SATS', 'SATISFACTORY'), ('GOOD', 'GOOD'), ('EXCL', 'EXCELLENT')], default='GOOD', max_length=4),
        ),
        migrations.AddField(
            model_name='feedback',
            name='A14',
            field=models.CharField(choices=[('POOR', 'POOR'), ('SATS', 'SATISFACTORY'), ('GOOD', 'GOOD'), ('EXCL', 'EXCELLENT')], default='GOOD', max_length=4),
        ),
        migrations.AddField(
            model_name='feedback',
            name='A15',
            field=models.CharField(choices=[('POOR', 'POOR'), ('SATS', 'SATISFACTORY'), ('GOOD', 'GOOD'), ('EXCL', 'EXCELLENT')], default='GOOD', max_length=4),
        ),
        migrations.AddField(
            model_name='feedback',
            name='A16',
            field=models.CharField(choices=[('POOR', 'POOR'), ('SATS', 'SATISFACTORY'), ('GOOD', 'GOOD'), ('EXCL', 'EXCELLENT')], default='GOOD', max_length=4),
        ),
        migrations.AddField(
            model_name='feedback',
            name='A17',
            field=models.CharField(choices=[('TS', 'Too Short'), ('AD', 'Adequate'), ('TL', 'Too Long')], default='AD', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='A18',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedbackquestions',
            name='Q13',
            field=models.TextField(default='Safety', max_length=100),
        ),
        migrations.AddField(
            model_name='feedbackquestions',
            name='Q14',
            field=models.TextField(default='Training Admin Response', max_length=100),
        ),
        migrations.AddField(
            model_name='feedbackquestions',
            name='Q15',
            field=models.TextField(default='Cafeteria', max_length=100),
        ),
        migrations.AddField(
            model_name='feedbackquestions',
            name='Q16',
            field=models.TextField(default='Sanitation', max_length=100),
        ),
        migrations.AddField(
            model_name='feedbackquestions',
            name='Q17',
            field=models.TextField(default='Whether Course Duration is', max_length=100),
        ),
        migrations.AddField(
            model_name='feedbackquestions',
            name='Q18',
            field=models.TextField(default='Course To Be recommended', max_length=100),
        ),
    ]
