# Generated by Django 3.0.2 on 2021-10-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedapp', '0004_auto_20211007_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='comments',
            field=models.TextField(default='No Comments', max_length=300),
        ),
    ]
