# Generated by Django 3.1.7 on 2021-10-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedapp', '0007_auto_20211013_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='subject',
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.CharField(default='Others', max_length=50),
        ),
    ]
