# Generated by Django 3.1.7 on 2021-10-14 16:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Feedapp', '0008_auto_20211014_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name_plural': 'Feedbacks'},
        ),
        migrations.AlterModelOptions(
            name='feedbackquestions',
            options={'verbose_name_plural': 'Feedback Questions'},
        ),
        migrations.AddField(
            model_name='course',
            name='end_time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='start_time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='A1',
            field=models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0, verbose_name='How well the course was organised?'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='A10',
            field=models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0, verbose_name='How do you rate the assistance provided during your training?'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='A11',
            field=models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0, verbose_name='How effective was the consultation provided?'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='A12',
            field=models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0, verbose_name='How well were the stated objectives of the module achieved?'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='A13',
            field=models.CharField(choices=[('POOR', 'POOR'), ('SATS', 'SATISFACTORY'), ('GOOD', 'GOOD'), ('EXCL', 'EXCELLENT')], default='GOOD', max_length=4, verbose_name='Safety'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='A14',
            field=models.CharField(choices=[('POOR', 'POOR'), ('SATS', 'SATISFACTORY'), ('GOOD', 'GOOD'), ('EXCL', 'EXCELLENT')], default='GOOD', max_length=4, verbose_name='Training Admin Response'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='A15',
            field=models.CharField(choices=[('POOR', 'POOR'), ('SATS', 'SATISFACTORY'), ('GOOD', 'GOOD'), ('EXCL', 'EXCELLENT')], default='GOOD', max_length=4, verbose_name='Cafeteria'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='A16',
            field=models.CharField(choices=[('POOR', 'POOR'), ('SATS', 'SATISFACTORY'), ('GOOD', 'GOOD'), ('EXCL', 'EXCELLENT')], default='GOOD', max_length=4, verbose_name='Sanitation'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='A17',
            field=models.CharField(choices=[('TS', 'Too Short'), ('AD', 'Adequate'), ('TL', 'Too Long')], max_length=2, verbose_name='Whether Course Duration is'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='A18',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=2, verbose_name='Course To Be recommended'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='A2',
            field=models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0, verbose_name='How confident do you feel about your grasp of this module content ?'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='A3',
            field=models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0, verbose_name='How do you rate the learning environment during your training?'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='A4',
            field=models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0, verbose_name='How satisfied you are by the training facility provided to you?'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='A5',
            field=models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0, verbose_name='How was the quality of study material provided to you?'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='A6',
            field=models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0, verbose_name='How effective do you find the faculty?'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='A7',
            field=models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0, verbose_name='How satisfactory did you find their answers to your queries?'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='A8',
            field=models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0, verbose_name='How thorough was their knowledge of course contents?'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='A9',
            field=models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0, verbose_name='How inspiring was your association with the faculty?'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comments',
            field=models.TextField(default='No Comments', max_length=300, verbose_name='How confident do you feel about your grasp of this module content ?'),
        ),
    ]
