# Generated by Django 3.1.7 on 2021-10-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedapp', '0010_auto_20211017_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='venue',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
