# Generated by Django 3.1.7 on 2021-10-20 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Feedapp', '0011_course_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_name', models.TextField(max_length=20, primary_key=True, serialize=False)),
                ('section', models.TextField(choices=[('CAD', 'CAD/CAM'), ('EB', 'Electronics Block'), ('CV', 'Civil')], default='CAD', max_length=10)),
                ('incharge', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
