# Generated by Django 3.1.7 on 2021-10-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedapp', '0012_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_name',
        ),
        migrations.AddField(
            model_name='course',
            name='course_details',
            field=models.CharField(default='nothing', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.TextField(choices=[('PGDTD', 'Post Graduate Diploma in Tool Design'), ('MCC', 'Master Certificate Course In CAD/CAM'), ('PDTDM', 'Post Diploma In Tool and Die Making'), ('PDCC', 'Post Diploma in CAD/CAM'), ('CNC', 'Computer Numeric Control'), ('ITI', 'ITI'), ('DDUGKY', 'DDUGKY'), ('CIVIL', 'CIVIL'), ('DTDM', 'Diploma In Tool and Die Making'), ('DIM', 'Diploma in Mechatronics'), ('MCCAPC', 'MCCAPC'), ('ADMA', 'ADMA'), ('IoT', 'Internet Of Things'), ('PE', 'Power Electronics'), ('VLSI', 'Very Large Scale Integration'), ('OT', 'Others')], max_length=20, primary_key=True, serialize=False),
        ),
    ]
